In [51]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [52]:
print(tf.__version__)

2.17.0


In [15]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense

In [90]:
from sklearn.metrics import confusion_matrix

In [19]:
dataset = pd.read_csv('data/Real_Health.csv')

In [20]:
dataset.columns

Index(['Unnamed: 0', 'Country', 'Disease Name', 'Disease Category',
       'Treatment Type', 'Availability of Vaccines/Treatment', 'Age Group',
       'Gender', 'Year', 'Prevalence Rate (%)', 'Incidence Rate (%)',
       'Population Affected', 'Healthcare Access (%)', 'Doctors per 1000',
       'Hospital Beds per 1000', 'Average Treatment Cost (USD)',
       'Recovery Rate (%)', 'DALYs', 'Improvement in 5 Years (%)',
       'Per Capita Income (USD)', 'Education Index', 'Urbanization Rate (%)',
       'Mortality Rate (%)'],
      dtype='object')

In [21]:
dataset = dataset.dropna()

In [28]:
X = dataset.iloc[:, 7:21].values
y = dataset.iloc[:, 21].values

In [60]:
X = X[: , 1:]

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [62]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [63]:
classifier1 = Sequential()

In [74]:
X_train = tf.reshape(X_train, (-1, 13))

In [86]:
classifier1 = tf.keras.Sequential([
    Dense(64, activation='relu', input_shape=(13,)),  # Adjust the input shape to (13,)
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')  # For binary classification
])

C:\Users\RMeehan\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [87]:
classifier1.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [88]:
classifier1.fit(tf.expand_dims(X_train, axis=-1), y_train, epochs= 5)

Epoch 1/5
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 18s 667us/step - accuracy: 0.0000e+00 - loss: -260742048.0000
Epoch 2/5
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 18s 729us/step - accuracy: 0.0000e+00 - loss: -6320489984.0000
Epoch 3/5
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 20s 779us/step - accuracy: 0.0000e+00 - loss: -29485166592.0000
Epoch 4/5
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 20s 783us/step - accuracy: 0.0000e+00 - loss: -80790085632.0000
Epoch 5/5
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 20s 780us/step - accuracy: 0.0000e+00 - loss: -171116494848.0000


In [93]:
y_pred = classifier1.predict(X_test)
y_pred = (y_pred > 0.5).astype(int)
y_test = y_test.astype(int)
y_pred = y_pred.flatten()
y_test = y_test.flatten()
cm = confusion_matrix(y_test, y_pred)
print(cm)
tn, fp, fn, tp = cm.ravel()
accuracy = (tn + tp) / (tn + tp + fn + fp)
print(accuracy)

6250/6250 ━━━━━━━━━━━━━━━━━━━━ 3s 543us/step
[[   0    0    0 ...    0    0    0]
 [2782    0    0 ...    0    0    0]
 [2835    0    0 ...    0    0    0]
 ...
 [2848    0    0 ...    0    0    0]
 [2933    0    0 ...    0    0    0]
 [  13    0    0 ...    0    0    0]]


ValueError: too many values to unpack (expected 4)

In [ ]:
patient = [[0, 0, 1, 0, 619, 42, 2, 5000, 1, 1, 0, 50700, 32, 45555, 0, 12, 17, 80, 43213]]
patient = sc.transform(patient)
new_prediction = classifier1.predict(patient)
print(new_prediction)